[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [build.environment]
  MONGO_URI = "mongodb+srv://cbhhamleton15_db_user:chahd123@cluster0.vspw0dt.mongodb.net/dietapp?retryWrites=true&w=majority&appName=Cluster0"

[context.production.environment]
  MONGO_URI = "mongodb+srv://cbhhamleton15_db_user:chahd123@cluster0.vspw0dt.mongodb.net/dietapp?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET = "set-a-strong-secret"
  NEXT_PUBLIC_BASE_URL = "https://glowing-churros-712251.netlify.app"
  NEXT_PUBLIC_ADMIN_EMAIL = "admin@example.com"
  APP_URL = "https://glowing-churros-712251.netlify.app"
  GOOGLE_CLIENT_ID=183873992354-mau1f8f7955t64co30c3h8do71besbkf.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET=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
  GMAIL_USER=dietopia62@gmail.com
  GMAIL_APP_PASSWORD=vyef zijv dmop oskn
